version: "3.8"
services:
  remark42:
    image: umputun/remark42:latest
    restart: unless-stopped
    environment:
      - REMARK_URL=https://comments.bysiva.blog
      - SITE=bysiva
      - AUTH_ANON=true
      - ADMIN_SHARED_ID=sambachinta.24@gmail.com
    ports:
      - "8080:8080"
    volumes:
      - remark42_db:/srv/var/db
      - remark42_backup:/srv/var/backup

volumes:
  remark42_db:
  remark42_backup:
